---
- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: true

- name: Install some packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - software-properties-common
    - git
    - htop
    - vim
    - imagemagick
    - libmagickwand-dev
  become: true

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true